### ISSUE TITLE
software install

### ISSUE THREAD

**Issue by HaoWangLYL** [mvolar/SatXplor#1]
when I install this software following your pipline. but the python version  which is given by this tools  are not enough for the requirements.txt.
ERROR: Ignored the following versions that require a different python version: 1.82 Requires-Python >=3.8; 1.83 Requires-Python >=3.8; 1.84 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement biopython==1.83 (from versions: 1.0a3, 1.0a4, 1.10, 1.20, 1.21, 1.22, 1.23, 1.24, 1.30, 1.40b0, 1.41, 1.42, 1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49b0, 1.49, 1.50b0, 1.50, 1.51b0, 1.51, 1.52, 1.53, 1.54b0, 1.54, 1.55b0, 1.55, 1.56, 1.57, 1.58, 1.59, 1.60, 1.61, 1.62b0, 1.62, 1.63b0, 1.63, 1.64, 1.65, 1.66, 1.67, 1.68, 1.69, 1.70, 1.71, 1.72, 1.73, 1.74, 1.75, 1.76, 1.77, 1.78, 1.79, 1.80, 1.81)
ERROR: No matching distribution found for biopython==1.83

**Comment by mvolar** [comment]
What is your python version?

**Comment by HaoWangLYL** [comment]
I got&nbsp; it, thank you&nbsp;
&nbsp;


635169288
***@***.***



&nbsp;

**Comment by HaoWangLYL** [comment]
But there isn't any scripts named " satxplor/run_all_tests.py"
and when i run the controller.py.   

IT alwasys error "FileNotFoundError: [Errno 2] No such file or directory: './results/data/sequences/'"

**Comment by mvolar** [comment]
you have to run it from the project main directory, how are you running the program?

**Comment by HaoWangLYL** [comment]
> you have to run it from the project main directory, how are you running the program?

YES , I had run it in the main dir, but  there isn't any scripts named " satxplor/run_all_tests.py"
and when i run  "python satxplor/controller.py "
2024-08-20 08:34:47,003 - INFO - Python Version:
2024-08-20 08:34:47,004 - INFO - 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:23:11) 
[GCC 9.4.0]
2024-08-20 08:34:47,004 - INFO - {'INPUT_GENOME_PATH': './testing_data/test_sequence.fasta', 'GENOME_PATH': './input.fasta', 'SAT_RAW': './testing_data/test_sats.fasta', 'SAT_FASTA_PATH': './sats.fasta', 'FINAL_RESULTS_DIR': './test_output/', 'OVERWRITE': True}
2024-08-20 08:34:47,028 - INFO - Last checkpoint is: extract at 2024-06-18 16:11:25.125771
2024-08-20 08:34:47,028 - INFO - The output folder already exists
Traceback (most recent call last):
  File "/public/home/software/repeatannote/satxplor/SatXplor/./satxplor/filename_mapping.py", line 49, in <module>
    main()
  File "/public/home/software/repeatannote/satxplor/SatXplor/./satxplor/filename_mapping.py", line 40, in main
    pairs = match_monomer_array_pairs(folder_path)
  File "/public/home/software/repeatannote/satxplor/SatXplor/./satxplor/filename_mapping.py", line 11, in match_monomer_array_pairs
    files = os.listdir(folder_path)
FileNotFoundError: [Errno 2] No such file or directory: './results/data/sequences/'
2024-08-20 08:34:47,439 - WARNING - Error. Return code:1
STDERR:
 None

**Comment by mvolar** [comment]
Do you have permissions to edit the folder? Try deleting the checkpoints file and run again.

**Comment by HaoWangLYL** [comment]
it work. thank you !
but there begin another error 
2024-08-20 21:23:38,207 - INFO - Pairs written to pairs.json
./satxplor/executables/kmer_edge_finder: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./satxplor/executables/kmer_edge_finder)
./satxplor/executables/kmer_edge_finder: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./satxplor/executables/kmer_edge_finder)
./satxplor/executables/kmer_edge_finder: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./satxplor/executables/kmer_edge_finder)
./satxplor/executables/kmer_edge_finder: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./satxplor/executables/kmer_edge_finder)
./satxplor/executables/kmer_edge_finder: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./satxplor/executables/kmer_edge_finder)
./satxplor/executables/kmer_edge_finder: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./satxplor/executables/kmer_edge_finder)
./satxplor/executables/kmer_edge_finder: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./satxplor/executables/kmer_edge_finder)
2024-08-20 21:23:38,230 - WARNING - Error. Return code:1
STDERR:
 None


635169288
***@***.***



&nbsp;

**Comment by mvolar** [comment]
What system are you using? The Rust application used by SatXplor is compiled on Ubuntu 22.04 and depends on GLIBC>2.32. You can manually compile the new binary on your older system by downloading Rust:

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

Restart your shell then navigate to the `satxplor/satxplor/executables/` folder then:

```
cargo build --release
cp /target/release/kmer_edge_finder ./
```

and application should run normally.
